### ISSUE TITLE
systemd service doesn't work on Debian

### ISSUE THREAD

**Issue by stevenroose** [horazont/xmpp-http-upload#6]
On Debian (3.16), `python3-flask` does not install the executable `/usr/bin/flask`. The systemd script relies on this executable, however.

**Comment by horazont** [comment]
The systemd service file is provided for convenience only. Due to the different ways how distributions handle python packages, we can’t provide a generic service file (unless by replicating the functionality of ``/usr/bin/flask``).

This isn’t the recommended way to operate the service in any case; using a proper web server with WSGI integration is preferred.

Sorry (from a fellow debian user).

**Comment by stevenroose** [comment]
Well, the README instructions describe installing Flask with `apt-get`,
which suggests Debian-based system, and using the systemd service.. Does
that example work in Ubuntu?

Do you know where a flask executable is located in Debian?

**Comment by horazont** [comment]
Debian stretch/stable does have the ``/usr/bin/flask`` executable in ``python3-flask``. So I guess this is only an issue on jessie/oldstable and below.
